version: '1.0'

services:
  app:
    build:
      context: .
    container_name: app_spring_boot
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=sorocaba468
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    networks:
      - my-network

  postgres:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sorocaba468
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge